tcc demo/Models/Plan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace tcc_demo.Models
{
    public class Plan
    {
        public string idPlan { get; set; }

        [Display(Name = "Nome do plano")]
        [Required(ErrorMessage = "Informe o nome do plano")]
        [MaxLength(80, ErrorMessage = "O nome do plano deve conter no maximo 255 caracteres")]
        public string namePlan { get; set; }



        [Display(Name = "Descrição do plano")]
        [Required(ErrorMessage = "Informe a descrição do plano")]
        [MaxLength(80, ErrorMessage = "a descrição do plano deve conter no maximo 255 caracteres")]
        public string descriptionPlan { get; set; }

        
        [Display(Name = "Preço do plano")]
        [Required(ErrorMessage = "Informe o preço do plano")]
        [RegularExpression(@"^[0-9]+${11,11}", ErrorMessage = "Somente números")]
        public double pricePlan { get; set; }

    }
}

tcc demo/Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using tcc_demo.Dados;
using tcc_demo.Models;

namespace tcc_demo.Controllers
{
    public class PlanController : Controller
    {
        AcPlan acPlan = new AcPlan();

        //[Authorize(Roles = "Admin")]
        public ActionResult CadPlan()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CadPlan(Plan plan)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.msg = "Erro ao realizar cadastro do plano";
                return View(plan);

            }
            else
            {
                acPlan.insertPlan(plan);
                ViewBag.msg = "Cadastro efetuado com sucesso";
                return RedirectToAction("Index", "Home");

            }
        }

        public ActionResult ListPlan()
        {
            return View(acPlan.getPlan());
        }

        public ActionResult DeletePlan(int id)
        {
            acPlan.deletePlan(id);
            return RedirectToAction("ListPlan");
        }


        public ActionResult UpdatePlan(string id)
        { 
            if (id == null)
            {
                return HttpNotFound();
            }
            return View(acPlan.getPlan().Find(model => model.idPlan == id));
        }

        [HttpPost]
        public ActionResult UpdatePlan(int id, Plan plan)
        {
            if (ModelState.IsValid)
            {
                plan.idPlan = id.ToString();
                acPlan.updatePlan(plan);
                return RedirectToAction("Index", "Home");
            }
            return View(plan);
        }
    
    public ActionResult Index()
        {
            return View();
        }
    }
}

tcc demo/Views/Plan/CadPlan.cshtml
@model tcc_demo.Models.Plan

@using (Html.BeginForm("CadPlan", "Plan", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <br />
    <div class="editor-label">
        @Html.LabelFor(m => m.namePlan)
    </div>

    <div class="editor-field">
        @Html.EditorFor(m => m.namePlan, new { htmlAttributes = new { @type = "text", } })
        @Html.ValidationMessageFor(model => model.namePlan, "", new { @class = "text-danger" })
    </div>
    <br />
    <div class="editor-label">
        @Html.LabelFor(m => m.descriptionPlan)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.descriptionPlan, new { htmlAttributes = new { @type = "text", } })
        @Html.ValidationMessageFor(model => model.descriptionPlan, "", new { @class = "text-danger" })
    </div>
    <br />
    <div class="editor-label">
        @Html.LabelFor(m => m.pricePlan)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.pricePlan, new { htmlAttributes = new { @type = "double", } })
        @Html.ValidationMessageFor(model => model.pricePlan, "", new { @class = "text-danger" })
    </div>
    <br />
    <input type="submit" value="Cadastrar" />
}
<br />
@ViewBag.msg

tcc demo/Views/Plan/ListPlan.cshtml
@model IEnumerable<tcc_demo.Models.Plan>


<h2>Listar Clientes</h2>


<table class="table">

    <tr>

        <th>

            @Html.DisplayNameFor(model => model.idPlan)

        </th>

        <th>

            @Html.DisplayNameFor(model => model.namePlan)

        </th>

        <th>

            @Html.DisplayNameFor(model => model.descriptionPlan)

        </th>

        <th>

            @Html.DisplayNameFor(model => model.pricePlan)

        </th>

        <th>

    </tr>



    @foreach (var item in Model)

    {

        <tr>

            <td>

                @Html.DisplayFor(modelItem => item.idPlan)

            </td>

            <td>

                @Html.DisplayFor(modelItem => item.namePlan)

            </td>

            <td>

                @Html.DisplayFor(modelItem => item.descriptionPlan)

            </td>

            <td>

                @Html.DisplayFor(modelItem => item.pricePlan)

            </td>


            <td>

                @Html.ActionLink("Atualizar", "UpdatePlan", new { id = item.idPlan }) |

                @Html.ActionLink("Excluir", "DeletePlan", new { id = item.idPlan }, new { onclick = "return confirm('Deseja realmente excluir?');" })

            </td>

        </tr>



    }



</table>

tcc demo/Views/Plan/UpdatePlan.cshtml
@model tcc_demo.Models.Plan
<div class="center">

    @using (Html.BeginForm("UpdatePlan", "Plan", FormMethod.Post, new { enctype = "multipart/form-data" }))

    {

        @Html.AntiForgeryToken()



        <div class="form-horizontal">

            <hr />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group space-around-flex">

                <div class="">

                    @Html.LabelFor(model => model.namePlan, htmlAttributes: new { @class = "control-label col-md-2" })

                </div>

                <div class="col-md-10">

                    @Html.EditorFor(model => model.namePlan, new { htmlAttributes = new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.namePlan, "", new { @class = "text-danger" })

                </div>

            </div>

            <div class="form-group space-around-flex">

                <div class="">

                    @Html.LabelFor(model => model.descriptionPlan, htmlAttributes: new { @class = "control-label col-md-2" })

                </div>

                <div class="col-md-10">

                    @Html.EditorFor(model => model.descriptionPlan, new { htmlAttributes = new { @class = "form-control"} })

                    @Html.ValidationMessageFor(model => model.descriptionPlan, "", new { @class = "text-danger" })

                </div>

            </div>



            <div class="form-group center">

                <div>

                    @Html.LabelFor(model => model.pricePlan, htmlAttributes: new { @class = "control-label col-md-2" })

                </div>

                <div class="col-md-10">

                    @Html.EditorFor(model => model.pricePlan, new
                    {
                        htmlAttributes = new
                        {
                            @class = "form-control",
                placeholder
                = "Digite a senha"
                        }
                    })

                    @Html.ValidationMessageFor(model => model.pricePlan, "", new { @class = "text-danger" })

                </div>

            </div>

       

            <div class="form-group center">

                <div class="col-md-10">

                    @ViewBag.msg <br />

                </div>

            </div>



            <div class="form-group">

                <div class="col-md-offset-2 col-md-10">

                    <input type="submit" value="Atualizar Cliente" class="btn btn-success" />

                </div>

            </div>

        </div>

    }

</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

}